version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      sam package --template-file template.yml --s3-bucket test-codebuild-bucket-435 --output-template-file packaged-template.yml
artifacts:
  type: zip
  files:
    - packaged-template.yml

