AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda canary deployment example
Resources:
  CountFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      CodeUri: ./src
      AutoPublishAlias: prod
      DeploymentPreference:
        Type: CodeDeployDefault.LambdaCanary10Percent5Minutes

  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: 404.html
    DeletionPolicy: Retain


  CopyCustomResource:
    Type: "AWS::CloudFormation::CustomResource"
    Properties:
      ServiceToken: !GetAtt CopyFunction.Arn

  CopyLayerVersion:
    Type: "AWS::Serverless::LayerVersion"
    Properties:
      ContentUri: ./copy.zip
      CompatibleRuntimes:
        - nodejs12.x
  
  CopyRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
      - PolicyName: S3CopyPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - s3:GetObject
            - s3:ListBucket
            - s3:PutObject
            - s3:PutObjectAcl
            Resource:
              - !Sub
                - arn:aws:s3:::${TargetBucket}/*
                - TargetBucket: !Ref S3Bucket
              - !Sub
                - arn:aws:s3:::${TargetBucket}
                - TargetBucket: !Ref S3Bucket

  CopyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./www
      Environment:
        Variables:
          BUCKET: !Ref S3Bucket
      Handler: copy.staticHandler
      Layers:
        - !Ref CopyLayerVersion
      Role: !GetAtt CopyRole.Arn
      Runtime: nodejs12.x
      Timeout: 300

Outputs:
  WebsiteURL:
    Value: !GetAtt
      - S3Bucket
      - WebsiteURL
    Description: URL for website hosted on S3